apiVersion: batch/v1
kind: CronJob
metadata:
  name: label-sysbox-nodes
  namespace: kube-system
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sysbox-labeler
          containers:
          - name: label-nodes
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              MAX_RETRIES=3
              SLEEP_INTERVAL=10

              i=1
              while [ $i -le $MAX_RETRIES ]; do
                echo "[$i/$MAX_RETRIES] Checking nodes..."
                changed=0

                for node in $(kubectl get nodes -o name); do
                  name=$(echo $node | cut -d'/' -f2)
                  label=$(kubectl get $node -o jsonpath='{.metadata.labels.sysbox-install}' 2>/dev/null)

                  if [ "$label" != "yes" ]; then
                    echo "Labeling $node"
                    kubectl label $node sysbox-install=yes --overwrite
                    changed=1
                  else
                    echo "$node already labeled."
                  fi
                done

                if [ "$changed" -eq 0 ]; then
                  echo "All nodes labeled. Done!"
                  break
                fi

                echo "Sleeping $SLEEP_INTERVAL seconds before retry..."
                sleep $SLEEP_INTERVAL
                i=$((i + 1))
              done
            resources:
              limits:
                memory: "128Mi"
                cpu: "100m"
          restartPolicy: OnFailure
